export const LOAD_REQUEST_USER = "SEARCH/LOAD_REQUEST_USER";
export const REQUEST_USER_WITH_ID = "SEARCH/REQUEST_USER_WITH_ID";
export const REQUEST_USER_WITH_ID_SUCCESS = "SEARCH/REQUEST_USER_WITH_ID_SUCCESS";
export const REQUEST_USER_WITH_ID_FAILURE = "SEARCH/REQUEST_USER_WITH_ID_FAILURE";